spring.application.name=Sujalam Agro Foods Backend

spring.datasource.url=${DB_URL:jdbc:mysql://sujalamagro.cpk6y6i0mrsc.eu-north-1.rds.amazonaws.com:3306/sujalam-agro-foods}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# App Properties
spring.jackson.default-property-inclusion=NON_NULL

